UI/MvcConciliacao/Controllers/AdministradoraController.cs
using Concillius.Application.Cadastros;
using Concillius.Application.Corporativo;
using Concillius.Domain.Cadastros;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcConciliacao.Controllers
{
    public class AdministradoraController : Controller
    {

        AdministradoraCartaoApplication app = null;

        public AdministradoraController()
        {
            app = new AdministradoraCartaoApplication();
        }

        public ActionResult Index()
        {
            var contas = app.GetAll();
            return View(contas);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new AdministradoraCartao());
        }

        [HttpPost]
        public ActionResult Create(AdministradoraCartao admin)
        {
            try
            {
                app.Save(admin);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id, int idEmpresa)
        {
            var admin = app.Get(id);
            return View(admin);
        }

        [HttpPost]
        public ActionResult Edit(int id, int idEmpresa, AdministradoraCartao admin)
        {
            try
            {
                app.Update(admin, id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id, int idEmpresa)
        {
            var admin = app.Get(id);
            return View(admin);
        }

        [HttpPost]
        public ActionResult Delete(int id, int idEmpresa, FormCollection collection)
        {
            try
            {
                var admin = app.Get(id);
                app.Delete(admin);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UI/MvcConciliacao/Controllers/ContaBancariaAdministradoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcConciliacao.Controllers
{
    public class ContaBancariaAdministradoraController : Controller
    {
        //
        // GET: /ContaBancariaAdministradora/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /ContaBancariaAdministradora/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /ContaBancariaAdministradora/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ContaBancariaAdministradora/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ContaBancariaAdministradora/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /ContaBancariaAdministradora/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ContaBancariaAdministradora/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /ContaBancariaAdministradora/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UI/MvcConciliacao/Controllers/ContaBancariaController.cs
using Concillius.Application.Cadastros;
using Concillius.Domain.Cadastros;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcConciliacao.Controllers
{
    public class ContaBancariaController : Controller
    {

        ContaBancariaApplication app = null;

        public ContaBancariaController()
        {
            app = new ContaBancariaApplication();
        }

        public ActionResult Index()
        {
            var contas = app.GetAll();
            return View(contas);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new ContaBancaria());
        }

        [HttpPost]
        public ActionResult Create(ContaBancaria conta)
        {
            try
            {
                conta = Auditoria(conta);
                app.Save(conta);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private ContaBancaria Auditoria(ContaBancaria conta)
        {
            conta.CodigoUsuarioInclusao = 49182;
            conta.DataInclusao = DateTime.Now;
            conta.CodigoUsuarioAlteracao = null;
            conta.DataAlteracao = null;

            return conta;
        }
        
        public ActionResult Edit(int id)
        {
            var conta = app.Get(id);
            return View(conta);
        }

        [HttpPost]
        public ActionResult Edit(int id, ContaBancaria conta)
        {
            try
            {
                app.Update(conta, id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            var conta = app.Get(id);
            return View(conta);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var conta = app.Get(id);
                app.Delete(conta);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UI/MvcConciliacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.js")" type="text/javascript"></script>    
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link  href="@Url.Content("~/Content/themes/bootstrap/css/bootstrap.min.css")" rel="stylesheet" type="text/css"/>
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/jquery/jquery-1.10.1.css")" rel="stylesheet" type="text/css"/>
    <link  href="@Url.Content("~/Content/Concillius.css")" rel="stylesheet" type="text/css"/>
    <link  href="@Url.Content("~/Content/forms.css")" rel="stylesheet" type="text/css"/>
    <meta name="viewport" content="width=device-width" />

</head>
   
    <body>
        <div class="row-fluid">
            <div class="span12">
            <div id="topo100" class="linkTopo">
                <div style="color: white; text-align: right; padding-right: 110px;">
                    <a  href="@Url.Action("PaginaInicial","Home")" style="text-decoration: none; color: white;"><img src="~/Images/pagina_inicial.gif" />&nbsp;&nbsp;Home</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    Usuário: @Session["Usuario"] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    
                </div>
            </div>
             
                <div class="row-fluid">
                <div class="span12">
                <div class="span1"></div>
                <div id="topo" class="span10">
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="span1"></div>
                            <div class="span2">
                                <h4>CONCILIAÇÃO DE CARTÃO</h4><br/>
                            </div>
                            <div class="span7"> </div>
                            <div class="span2">
                                <img src="~/Images/logo.ico" />
                            </div>

                        </div>
                     </div>
                </div>
                 </div>
                    <div class="row-fluid">
                        <div class="span1"></div>
                        <div class="span10">
                            @Html.Partial("_Menu")   
                            
                            <div class="article">
                                
                                <div class="row-fluid">
                                    <div class="span12 siteMap">
                                        @RenderSection("featured", required: false)
                                     </div>
                                </div>
                            
                                    <div class="row-fluid">
                                    <div class="span12">
                                        <div class="content-wrapper">
                                            @RenderBody()
                                            <div id="modal"></div>
                                            <div id="inner-modal"></div>
                                            <div id="dialog"></div>
                                            <div id="confirm"></div>
                                            <div id="domMessage" style="display:none;"><h1><img  src="~/Images/ui-anim_basic_16x16.gif" /> </h1> </div>     
                                        </div>  
                                    </div>
                                </div>
                            </div>
                            <div class="footer">
                                <p class="site-title">&copy; @DateTime.Now.Year - Concillius | contato@concillius.com.br | Tel: (85) 9988-8331</p>
                            </div>
                        </div>
                        <script src="@Url.Content("~/Scripts/jquery.meiomask.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/bootstrap/bootstrap.min.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript")"></script>
                        <script src="@Url.Content("~/Scripts/cosmos-buttons.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/onload-app.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/MicrosoftAjax.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/MicrosoftMvcAjax.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/MicrosoftMvcValidation.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/cosmos-functions.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/cosmos-modal.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/cosmos-accordion.js")" type="text/javascript"></script>        
                        <script src="@Url.Content("~/Scripts/cosmos-tabs.js")" type="text/javascript"></script>
                        <script src="@Url.Content("~/Scripts/listBoxDouble.js")" type="text/javascript"></script>       
                        <!--<script src="@Url.Content("~/Scripts/jquery.blockUI.min.js")"></script>
                        <script src="@Url.Content("~/Scripts/jquery.blockUI.js")"></script>-->
                    </div>
            </div>   
            </div> 
            </div>
    </body>

</html>

UI/MvcConciliacao/Views/Shared/_Menu.cshtml
<div class="navbar">
    <div class="navbar-inner">
        <ul class="nav" role="navigation">
            <li class="dropdown">
                <a id="cadastro" role="button" data-toggle="dropdown" class="dropdown-toggle">Cadastros
                    <div class="caret"></div>
                </a> 
                <ul id="cadastro" class="dropdown-menu" role="menu" aria-labelledby="drop1">
                    <li>@Html.ActionLink("Administradora de Cartões", "Index", "Administradora", null, null)</li>
                    <li>@Html.ActionLink("Conta Bancária", "Index", "ContaBancaria", null, null)</li>
                    <li>@Html.ActionLink("Conta Bancária da Administradora", "Index", "ContaBancariaAdministradora", null, null)</li>
                    <li>@Html.ActionLink("Filial", "Index", "Filial", null, null)
                    <li >@Html.ActionLink("Maquineta","Index","Maquineta",null, null)</li>                    
                    <li>@Html.ActionLink("Parâmetros da Administradora", "Index", "Parametros", null, null)</li>
                    <li>@Html.ActionLink("Resumo de Atualizações", "Index", "ResumoAtualizacao", null, null)</li>
                </ul>
            </li>
              <li class="dropdown">
                <a id="consultas" role="button" data-toggle="dropdown" class="dropdown-toggle">
                    Exportações/Consultas
                    <div class="caret"></div>
                </a>
                <ul id="consultas" class="dropdown-menu" role="menu" >
                     <li>@Html.ActionLink("Ajustes", "Index", "ExportacaoAjustes", null, null)</li>
                     <li>@Html.ActionLink("Parametrizadas", "Index", "Parametrizada", null, null)</li>
                     <li>@Html.ActionLink("Divergências de Vendas", "Index", "DivergenciaVenda", null, null)</li>
                    <li>@Html.ActionLink("Fechamento Diário", "Index", "FechamentoDiario", null, null)</li>
                    <li>@Html.ActionLink("Gerenciamento Importações", "Index", "GerenciamentoImportacao", null, null)</li>
                    <li>@Html.ActionLink("Movimentação Cupons", "Index", "MovimentacaoCupom", null, null)</li>
                    <li>@Html.ActionLink("Recebimentos", "Index", "Recebimentos", null, null)</li>
                    <li>@Html.ActionLink("Saldos", "Index", "Saldo", null, null)</li>
                    <li>@Html.ActionLink("Tarifas", "Index", "Tarifa", null, null)</li>
                    <li>@Html.ActionLink("Vendas", "Index", "Venda", null, null)</li>
                </ul>

            </li>
             <li class="dropdown">
                <a id="integracao" role="button" data-toggle="dropdown" class="dropdown-toggle">
                    Integração
                    <div class="caret"></div>
                </a>
                  <ul id="integracao" class="dropdown-menu" role="menu" >
                      <li>@Html.ActionLink("Importação de Vendas", "Buscar", "ImportacaoVenda", null, null)</li>
                      <li>@Html.ActionLink("Importação de Extratos Bancários", "Buscar", "ImportacaoExtrato", null, null)</li>
                      <li>@Html.ActionLink("Exportar Planilha", "Buscar", "ExportarPlanilha", null, null)</li>
                  </ul>
            </li>
            <li class="dropdown">
                <a id="movimentacao" role="button" data-toggle="dropdown" class="dropdown-toggle">
                    Movimentação
                    <div class="caret"></div>
                </a>
                  <ul id="movimentacao" class="dropdown-menu" role="menu" >
                        <li>@Html.ActionLink("Ajustes", "Index", "Ajustes", null, null)</li>
                        <li>@Html.ActionLink("Antecipação", "Index", "Antecipacao", null, null)</li>
                        <li>@Html.ActionLink("Cupom Manual", "Index", "CupomManual", null, null)</li>
                        <li>@Html.ActionLink("Deslocamento de Parcelas", "Index", "DeslocamentoParcela", null, null)</li>
                        <li>@Html.ActionLink("Recebimento", "Index", "Recebimento", null, null)</li>
                        <li>@Html.ActionLink("Solicitacão de Ajustes", "Index", "SolicitacaoAjuste", null, null)</li>
                        <li>@Html.ActionLink("Tarifa", "Index", "Tarifa", null, null)</li>
                        <li>@Html.ActionLink("Venda", "Index", "Venda", null, null)</li>
                  </ul>
            </li>
        </ul>
    </div>
</div>